### ISSUE TITLE
Uruchamianie lokalnie

### ISSUE THREAD

**Issue by tometchy** [devWarsztaty/devWarsztaty.github.io#63]
Jak wy odpalacie te stronę lokalnie, tak żeby CSSy działały?

Jak odpalam z pliku, albo z webserwera wbudowanego w _Ridera_ , to mam błąd:
`Refused to apply style from 'http://localhost:63342/css/font-awesome.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Działa bez problemu gdy zainicjalizowałem Jekylla, mogę Wam zrobić pull requesta, wtedy wystarczy odpalać `bundle exec jekyll serve --incremental` (w GitHub pages nie trzeba nic zmieniać, skoro obecnie działa dobrze bez Jekylla), ale jestem ciekaw jak teraz to odpalacie, może macie lepszy sposób? :)

**Comment by ptrstpp950** [comment]
Pewnie każdy z nas inaczej, ale u mnie działa http-server z npm (` npm install http-server -g`)

I w katalogu: `http-server.cmd`

**Comment by tometchy** [comment]
Ok, dzięki :) Można już to issue zamknąć, chodziło mi tylko o tę odpowiedź.

Swoją drogą, to nie wolicie sobie to wszystko oprzeć o Jekylla? To bardzo ułatwia zarządzanie i jednocześniej jest bardzo proste. W dodatku Jekyll jest dość _liberalny_, dzięki czemu dotychczasowy content może zostać tak jak jest, nie trzeba tego wszystkiego w jakiś sposób migrować, można zacząć dodawać nowe wydarzenia/prelegentów po Jekyllowemu, a stare zostawić tak jak jest.

Dla przykładu strona _wydarzenie_ ma swój szablon, w którym jest do uzupełnienia data, tytuł, opis, prelegenci, opis itd.
Wówczas dodanie nowego wydarzenia, to stworzenie nowego pliku tekstowego, wybranie szablonu _wydarzenie_ i uzupełnienie wymaganych treści, które zostaną wkomponowane w odpowiednie miejsce w szablonie i tyle :)
A gdy zmienisz np. bio prelegenta, to zaktualizuje się we wszystkich stronach wydarzeń, w których brał udział, nie tak jak jest obecnie, że trzeba ręcznie w każdym pliku zaktualizować.

Przerobiłem na jekylla już kilka stron statycznych stron, jakbyście chcieli iść w tę stronę to chętnie pomogę :)

**Comment by ptrstpp950** [comment]
@tometchy jak masz ochotę to przerób. Kiedyś to powstało i nikt nie było potrzeby zmiany. Czujesz -> działaj

**Comment by tometchy** [comment]
Włożona praca jest niewielka, a uproszczenie zarządzania stroną jest odczuwalne, w wolnej chwili Wam przerobię :)
